#!/bin/bash
#ban all peers more than 10 blocks behind blockbook and repeat until none are found
#set the bantime in seconds (31536000s = 1 year) (86400s = 1 day)
BanTime=86400
MaxBlocksBehind=10
FoundBadPeer=true
while [ $FoundBadPeer = true ]
do
    FoundBadPeer=false
    CurrentBlock=$(curl https://blockbook.polispay.org 2>&1 | grep -o 'href=\"/block/[^\"]*'| sed 's/^.*block\///')
    echo "Current Block is: $CurrentBlock"
    PeerInfo=`/usr/local/bin/polis-cli -conf=/root/.poliscore/polis.conf getpeerinfo`
    PeerList=`echo "$PeerInfo" | grep 'addr\": \"' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
    #echo "$PeerList"
    for Peer in $PeerList
    do
        Blocks=`echo "$PeerInfo" | grep -A 20 "addr\": \"$Peer" | grep starting | grep -o '[0-9]\{1,9\}'`
        #some peer IPs can have multiple matches
        for Block in $Blocks
        do
            BlocksBehind=$(($CurrentBlock-$Block))
            if [ $BlocksBehind -gt $MaxBlocksBehind ];
            then
                /usr/local/bin/polis-cli -conf=/root/.poliscore/polis.conf setban $Peer add $BanTime 2>&1
                echo "Banning Peer $Peer for being on Block: $Block"
                FoundBadPeer=true
            fi
        done
    done
#echo "end of iteration"
#/usr/local/bin/polis-cli -conf=/root/.poliscore/polis.conf getpeerinfo | grep starting
sleep 10
done
